name: Deploy to Amazon Lightsail

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  DEPLOY_PATH: '/home/ubuntu/Lucs-Project'

jobs:

  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}



    # --- FRONTEND TESTING ---
    - name: Test Frontend
      run: |
        cd Front-end
        npm install
        chmod +x ./node_modules/.bin/jest
        npm test

        

    # --- CodeCov ---
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    # --- BACKEND TESTING ---
    - name: Test Backend
      env:
        NODE_ENV: test
        # Dummy variables just in case your config requires them to not be undefined
        DB_HOST: localhost 
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      run: |
        cd Back-end
        npm install
        npm test 

    # --- DEPLOYMENT ---
    # This step ONLY runs if BOTH testing steps above pass successfully.
    - name: Copy Files to Lightsail (SCP)
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ubuntu
        key: ${{ secrets.LIGHTSAIL_KEY }}
        source: "."
        target: ${{ env.DEPLOY_PATH }}

      

    - name: Restart Server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ubuntu
        key: ${{ secrets.LIGHTSAIL_KEY }}
        script: |
          cd ${{ env.DEPLOY_PATH }}/Back-end
          npm install --production
          pm2 restart municipal-api || pm2 start server.js --name "municipal-api"
          pm2 save

      